-- 코드를 입력하세요
SELECT
    T3.HISTORY_ID,
    CAST((T3.DAILY_FEE - ((T3.DAILY_FEE * IFNULL(T4.DISCOUNT_RATE, 0)) / 100))* T3.DAYS AS SIGNED) AS FEE
FROM
(
    SELECT
        T1.HISTORY_ID,
        T2.CAR_TYPE,
        T1.START_DATE,
        T1.END_DATE,
        T2.DAILY_FEE,
        DATEDIFF(T1.END_DATE, T1.START_DATE) + 1 AS DAYS,
        CASE WHEN DATEDIFF(T1.END_DATE, T1.START_DATE) + 1 >= 90 THEN '90일 이상'
             WHEN DATEDIFF(T1.END_DATE, T1.START_DATE) + 1 >= 30 THEN '30일 이상'
             WHEN DATEDIFF(T1.END_DATE, T1.START_DATE) + 1 >= 7 THEN '7일 이상'
             ELSE '7일 이하' END AS 'RENT_DAYS'
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY T1
    LEFT JOIN CAR_RENTAL_COMPANY_CAR T2 ON T1.CAR_ID = T2.CAR_ID
    WHERE
        T2.CAR_TYPE = '트럭') T3
LEFT JOIN (
    SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE='트럭') T4 ON T3.RENT_DAYS = T4.DURATION_TYPE
ORDER BY FEE DESC, T3.HISTORY_ID DESC;
